displayName=Brimtstone and Elven Chest Tracker
author=H4waiianPunch
description=Stats for Brimstone and Elven Chests
support=https://github.com/H4waiianPunch/Brimstone-and-Elven-Chest-Tracker
tags=brimstone,elven,chest,konar,dusk,dragonstone
plugins=com.BrimstoneElvenChestTracker.BrimstoneElvenChestTrackerPlugin
build=standard